#!/bin/bash
# -*- coding: utf-8 -*-
#
#  drauger-installer
#  
#  Copyright 2018 Thomas Castleman <draugeros@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
version="0.1.2"
if [ "$1" == "--version" ]; then
	echo -e "\ndrauger-installer version $version\n"
	exit 0
fi
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
	echo -e "\nJust run drauger-installer to get a GUI installer for a *.deb package.\nOr, pass drauger-installer the file path to install via a CLI.\n"
	exit 0
fi
if $(echo "$1" | grep -q '.deb') && $(echo "$1" | grep -q '/'); then
	pak=$(dpkg-deb -f $1 Package)
	ver=$(dpkg-deb -f $1 Version)
	des=$(dpkg-deb -f $1 Description)
	dep=$(dpkg-deb -f $1 Depends)
	info="Package: $pak

Version: $ver

Depends: $dep

Description: $des

"
	if $(dpkg -l "$pak" | grep -q "$pak"); then
		action="update"
		actioned="updated"
	else
		action="install"
		actioned="installed"
	fi
	read -p "$info Would you like to $action this package? [y/N]: " ans
	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
		{ 
			sudo apt -y install "$1" && echo -e "\n$pak has been $actioned\n"
		} && {
			exit 0
		} || exit 2
	else
		exit 1
	fi
elif $(echo "$1" | grep -q '.deb'); then
	pak=$(dpkg-deb -f $1 Package)
	ver=$(dpkg-deb -f $1 Version)
	des=$(dpkg-deb -f $1 Description)
	dep=$(dpkg-deb -f $1 Depends)
	info="Package: $pak

Version: $ver

Depends: $dep

Description: $des

"
	if $(dpkg -l "$pak" | grep -q "$pak"); then
		action="update"
		actioned="updated"
	else
		action="install"
		actioned="installed"
	fi
	read -p "$info Would you like to $action this package? [y/N]: " ans
	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
		{ 
			sudo apt -y install ./"$1" && echo -e "\n$pak has been $actioned\n"
		} && {
			exit 0
		} || exit 2
	else
		exit 1
	fi
fi
zenity --info --text="Welcome to Drauger Installer! In the following screen, please navigate to the *.deb file you wish to install, select it, then hit \"Ok\"" --no-wrap
install=$(zenity --file-selection --file-filter=*.deb)
if [ "$?" == "1" ]; then
	exit 1
else
	
	pak=$(dpkg-deb -f $install Package)
	ver=$(dpkg-deb -f $install Version)
	des=$(dpkg-deb -f $install Description)
	dep=$(dpkg-deb -f $install Depends)
	info="Package: $pak 

Version: $ver

Depends: $dep

Description: $des"
fi
if $(dpkg -l "$pak" | grep -q "$pak"); then
		action="update"
		actioned="updated"
	else
		action="install"
		actioned="installed"
	fi
zenity --question --no-wrap --text="Package Info:\n\n$info\n\nWould you like to $action this package?"
x="$?"
if [ "$x" == "0" ]; then
	( pkexec apt -y install "$install" | zenity --progress --pulsate --auto-close --no-cancel --text="Installing $pak . . ." && notify-send "$pak has been $actioned" ) || zenity --error --no-wrap --text="An error was encountered installing your app. Error code $? was thrown from apt."
else
	exit 1
fi
