#!/bin/bash
# -*- coding: utf-8 -*-
#
#  drauger-installer
#  
#  Copyright 2018 Thomas Castleman <draugeros@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
install=$(zenity --file-selection --file-filter=*.deb)
zenity --question --no-wrap
x="$?"
if [ "$x" == "0" ]; then
	({
		pkexec apt install "$install" | zenity --progress --pulsate --auto-close --no-cancel --time-remaining
	} && {
		notify-send "Your app has been installed"
	}) || {
		zenity --error --no-wrap --text="An error was encountered installing your app. Error code $? was thrown from apt."
	}
else
	exit 1
fi
