.\" Manpage for drauger-installer.
.\" Contact draugeros@gmail.com to correct errors or typos.
.TH man 8 "15 November 2018" "0.0.8" "drauger-installer man page"
.SH NAME
drauger-installer \-  Gdebi Alternative
.SH SYNOPSIS
drauger-installer is a simple Gdebi Alternative for Ubuntu 18.04 and later and it's derivatives.
.SH DESCRIPTION
drauger-installer allows users to install raw *.deb files onto their systems if Gdebi does not work. It also has a CLI interface in case it needs to be used from tty.
.SH USAGE
To use drauger-installer from CLI, pass drauger-installer the path to the *.deb file you wish to install. It will promp you
for the appropriate input when needed.
.SH OPTIONS
-h	Print the Help dialoge and exit
.SH BUGS
No known bugs.
To report a bug please visit https://github.com/Batcastle/drauger-installer/issues
.SH AUTHOR
Thomas Castleman (draugeros@gmail.com)
